La statistique est l'outil qui, en sciences, permet d'étudier le *hasard* : le décrire, l'analyser, distinguer différents types de hasard, séparer ce qui est dû au hasard et ce qui ne l'est pas. 

La statistique se parle en langage mathématique, et ce cours ne fera pas exception à cette règle ; mais elle ne s'y réduit pas. Qu'on le veuille ou non, sa puissance a fait d'elle un outil omniprésent dans tous les domaines de la vie où des phénomènes sont *mesurés* et *quantifiés*, qu'il s'agisse de science, d'industrie, de commerce ou de politique. Depuis quelques dizaines d'années, les idées venues de la statistique ont même donné à des problèmes purement mathématiques (et parfois anciens) un nouvel éclairage ; certaines des questions les plus ardues de mathématiques pures sont de nature statistique. 

Dans ce cours, mon objectif est vous apprendre à penser en statistique, quel que soit le domaine auquel vous vous destinez. On apprendra donc : 

- tout ce qui permet de **décrire les lois du hasard** (familles de lois classiques, moyennes, médianes, quartiles, écrasement, queues de probabilités, indices de dispersion et d'inégalité, distances entre lois, etc.)
- les techniques élémentaires pour **retrouver des paramètres à partir d'observations** (estimation, intervalles de confiance, tests, régression)
- certains des liens entre statistiques, théorie de l'information, physique statistique et machine learning (maximum de vraisemblance, entropie, théorème de Shannon, bornes informationnelles) ;
- la quantification de l'incertitude du savoir extrait des observations, c'est-à-dire **le point de vue Bayésien** ; 
- et enfin, ce qui n'est pas courant, une grande partie du cours sera consacrée aux **phénomènes extrêmes et aux lois à queue lourde** (théorème de Fisher-Tippett-Gnedenko, lois stables, estimation). 




## Organisation {.unnumbered}

- Le cours a lieu tout le second semestre, du 8 janvier au 3 avril, avec une semaine de vacances du 2 au 7 mars. 

- Les CM ont lieu le mercredi de 13h45 à 15h15 en salle 1009 et le vendredi de 8h30 à 10h en salle 1009. 

- Les TD sont assurés par Hugo Capot et ont lieu le mercredi de 15h30 à 17h30 en salle 1009 et le vendredi de 10h45 à 12h45 en salle 1009. 

- Le CC2 aura lieu la semaine du 23 mars. 








## Utiliser ce site

Chaque chapitre de ce livre contient une page dédiée au cours théorique, et une page d'exercices. 

Ces notes sont mises en lignes et totalement accessibles via [Quarto](https://quarto.org). Si vous savez comment utiliser `git`, n'hésitez pas à corriger toutes les erreurs que vous pourriez voir (et Dieu sait qu'elles seront nombreuses) via des pull requests. 


<!--\newcommand{\bx}{\boldsymbol{x}}
\newcommand{\bmu}{\boldsymbol{\mu}}
\newcommand{\bt}{\boldsymbol{\theta}}
\newcommand{\dkl}{\mathrm{d}_{\mathrm{KL}}}
\newcommand{\dtv}{\mathrm{d}_{\mathrm{TV}}}
\newcommand{\tr}{\mathrm{tr}}-->


